### ISSUE TITLE
templates folder and static folder not installed if using pip

### ISSUE THREAD

**Issue by fabiocaccamo** [jaredly/django-colorfield#14]
**TemplateDoesNotExist** -> colorfield/color.html
"templates" folder and "static" folder are not included in the dist package.

![schermata 2015-11-04 alle 15 13 15](https://cloud.githubusercontent.com/assets/1035294/10940469/ca9ce97a-8306-11e5-82bf-777e80e57e0e.png)

I think the problem is in MANIFEST.in or in setup.py, 
could you fix it? I need to use django-colorfield as an external dependency of another package.

**Comment by aidan2129** [comment]
+1
