### ISSUE TITLE
Default color not reflecting

### ISSUE THREAD

**Issue by snig-b** [jaredly/django-colorfield#17]
I have given a default hex value (**'#FFC107'**) in the model field. But the widget still gets initialized with **#FFFFFF** .
Any clue as to why this is happening?

**Comment by fabiocaccamo** [comment]
With which Django version did you issue the problem?

**Comment by snig-b** [comment]
Hey, I am Django 1.6.5

**Comment by snig-b** [comment]
Any updates on this? I debugged it and seems the value context variable for colorfield widget is being set None, shouldn't it receive the color I gave as default. I went in deeper in django libraries and failed to find out what the problem is... since it is None, jscolor.js changes it to #FFFFFF .

**Comment by fabiocaccamo** [comment]
Sorry, I had not yet the time to investigate it.
I can tell you that I'm using django-colorfield as dependency of the [django-admin-interface](https://github.com/fabiocaccamo/django-admin-interface/) app and default value works.
Could you try to test it on a more recent django version ?

**Comment by gtnx** [comment]
Same for me. It works fine. Please provide more info

**Comment by snig-b** [comment]
Seemed to work on a newer version. If I face the problem again I'll request a reopen then. You can close the issue. Thanks
