### ISSUE TITLE
Why is max_length = 10?

### ISSUE THREAD

**Issue by danielquinn** [jaredly/django-colorfield#27]
Given that a hex colour is at most 7 characters (including the `#`), why is `max_length` set to `10` on [this line](https://github.com/jaredly/django-colorfield/blob/master/colorfield/fields.py#L28)?

Thanks a lot for this project.  I understand that you're not actively developing on Django anymore, but this appears to still be the best one out there, so I'm going to use it anyway.

**Comment by fabiocaccamo** [comment]
An alpha-hex color is 8 characters (9 including the `#`).
