### ISSUE TITLE
License incompatibility?

### ISSUE THREAD

**Issue by danielquinn** [jaredly/django-colorfield#30]
Given that jscolor is GPL3, doesn't that mandate that django-colorfield must *also* be GPL3?

**Comment by fabiocaccamo** [comment]
Good question...frankly I don't know. Could you investigate it?

**Comment by danielquinn** [comment]
I'm not a legal expert, but as best I can tell, the licenses *are* compatible, but if distributed together, [the GPL supersedes the MIT license](http://stackoverflow.com/a/11752204/231670).  So legally speaking (if my reading is correct) you'd either have to re-license under the GPL or remove the GPL component library, replacing it with instructions on how to acquire it and make it available to the wider project.

Obviously the latter is a pain in the ass, while the former is a philosophical question.  Given that you're freely distributing this project anyway, I'm not sure it matters, but would-be users of the project should know that strictly speaking, this is actually a GPL project due to the inclusion of colorjs.

**Comment by fabiocaccamo** [comment]
Reading stackoverflow:

> **Can I include GPL licensed code in a MIT licensed product?**
> You can. GPL is free software as well as MIT is, both licenses do not restrict you to bring together the code where as "include" is always two-way.

Since it's not really clear, we continue with the MIT License.
