### ISSUE TITLE
MEDIA_URL in fields.py

### ISSUE THREAD

**Issue by mattots** [jaredly/django-colorfield#8]
Shouldn't this be STATIC_URL? Otherwise it's trying to find colorfield/jscolor.js in my client-uploaded media directory!

**Comment by fabiocaccamo** [comment]
It has been fixed.

**Comment by phoebebright** [comment]
Or even no path at all.  The current version fails in django 1.8.5 as settings are not yet available.
Can do pull request with this change, if you think this is the right way to go:

        try:
             js = [settings.STATIC_URL + 'colorfield/jscolor/jscolor.js']

**Comment by fabiocaccamo** [comment]
@phoebebright have you tried the latest release?

**Comment by phoebebright** [comment]
The problems I was having were to do with my test environment (oops), however django suggested format for form media files now does not include the STATIC_URL so I left that part of the comment in.  Feel free to ignore!
